version: '3.8'

services:

  capman_web:
    build: 
      context: ./services/web
      dockerfile: Dockerfile.prod
    container_name: capman_web
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - ./services/web/:/usr/src/app/
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    expose:
      - 5000:5000
    env_file:
      - ./.prod.env
    depends_on:
      - capman_db

  capman_db:
    image: postgres:13-alpine
    container_name: capman_db
    volumes:
      - ./postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.prod.db.env

  capman_nginx:
    build: ./services/nginx
    container_name: capman_nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    depends_on:
      - capman_web

volumes:
  static_volume:
  media_volume: