# pull official base image
FROM python:3.9.5-slim-buster

RUN mkdir /app

# set work directory
WORKDIR /app

ADD requirements.txt /app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONBUFFERED 1
ENV FLASK_ENV local

# install system dependencies
RUN apt-get update && apt-get install -y netcat

# install dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy all files
COPY . /app

EXPOSE 8080
EXPOSE 5000

# run entrypoint
RUN chmod +x ./entrypoint.sh
ENTRYPOINT ["sh", "entrypoint.sh"]